[general]
output_dir = "outputs/imagenet/transfer/multi/"
model_flags = ["openclip", 'openclip_rn50']
target_model_flag = "imagebind"
gpu_nums = [ 0, 1]
epochs = [ 50, 75, 100, 150, 200, 250, 300,]
batch_size = 4
epsilon = 16
zero_shot_steps = 1
lr = 0.02
eta_min = 1e-5
seed = 0
number_images = 100
gamma_epochs = 300
modality = "vision"
dataset_flag = "imagenet"
jpeg=true
save_all=true
