[general]
output_dir = "outputs/imagenet/whitebox/audioclip/"
model_flag = "audioclip"
gpu_num = 0
epochs = [ 50, 75, 100, 150, 200, 250, 300,]
batch_size = 4
epsilon = 16
zero_shot_steps = 1
lr = 0.02
eta_min = 1e-5
seed = 0
number_images = 100
gamma_epochs = 300
modality = "vision"
dataset_flag = "imagenet"
